# Generated by Django 4.2.1 on 2023-07-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_reply_image_reply_likes_likereply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeeksModel',
        ),
    ]
