# Generated by Django 4.2.1 on 2023-07-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_delete_geeksmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='network/images/profile_images/'),
        ),
    ]
